# default-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default  # Specify the namespace where the Service Account resides
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded value of 'admin'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'