apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: interceptor-role
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["interceptors"]
    verbs: ["get", "list", "watch",  "create", "update", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: interceptor-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: default
roleRef:
  kind: Role
  name: interceptor-role
  apiGroup: rbac.authorization.k8s.io
